<div class="row">
    <form class="form" method="post">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Proyecto</label>
                <select class="form-control" id="selectProyecto" name="selectProyecto" id="selectProyecto" onchange="cargarTrabajos(this)">
                    <option value="">Seleccione un Proyecto...</option>
                    <?php if ($this->_proyectos) {
                        foreach ($this->_proyectos as $p){ 
                            if($p->getId_producto() == $this->_proyectoSeleccionado){?>
                                 <option selected value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                            <?php }else { ?>
                            <option value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                        <?php }    }              
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Trabajo</label>
                <select class="form-control"  name="selectTrabajo" id="selectTrabajo" onchange="cargarEventos(this)">
                    <option value="">Seleccione un Trabajo...</option>
                    <?php if ($this->_trabajo) {
                        
                        foreach ($this->_trabajo as $t) { 
                            if($t->getIdHito() == $this->_trabajoSeleccionado){ ?>
                                 <option selected value="<?php echo $t->getIdHito() ?>"><?php echo $t->getNombre() ?></option>
                            <?php }else { ?>                                              
                            <option value="<?php echo $t->getIdHito() ?>"><?php echo $t->getNombre() ?></option>                                        
                        <?php  } }
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Evento</label>
                <select class="form-control" name="selectEvento" onchange="cargarAreas(this)">
                    <option value="">Seleccione un Evento...</option>
                    <?php if ($this->_evento) {
                        foreach ($this->_evento as $e) { 
                            if($e->getIdEvento() == $this->_eventoSeleccionado){ ?>
                                 <option selected value="<?php echo $e->getIdEvento() ?>"><?php echo $e->getNombreEvento() ?></option>
                            <?php }else { ?>                                              
                            <option value="<?php echo $e->getIdEvento() ?>"><?php echo $e->getNombreEvento() ?></option>                                        
                    <?php  } 
                        }
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Área</label>
                <select class="form-control" name="selectArea">
                    <option value="">Seleccione un Área...</option>
                    <?php if ($this->_areas) {
                        foreach ($this->_areas as $a) { ?>                                              
                            <option value="<?php echo $a->getIdArea() ?>"><?php echo $a->getNombre() ?></option>                                        
                    <?php  } 
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Nombre del Servicio</label>
                <input type="text" name="txtNombreServicio" class="form-control">
            </div>
        </div>
         <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Descripción del Servicio</label>
                <input type="text" name="txtDescripcionServicio" class="form-control">
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group text-right">
                    <button type="submit" id="btn" class="btn btn-yellow" onclick="Servicio.prototype.procesoEnviaForm('form', '<?php echo BASE_URL ?>servicio/ingresar', 'btn', '<?php echo BASE_URL ?>servicio')">Guardar</button>
            </div>
        </div>
    </form>
</div>

<script>
    
    function cargarTrabajos(s){
      
        var idProyecto = s[s.selectedIndex].value; 
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/servicio/nuevo/'+idProyecto, 'Nuevo Servicio', '');
    }
    
    function cargarEventos(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        var idTrabajo = s[s.selectedIndex].value; 
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/servicio/nuevo/'+ idProyecto + '/' + idTrabajo, 'Nuevo Servicio', '');
    }
    
    function cargarAreas(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        alert(idProyecto);
        var idTrabajo = $( "#selectTrabajo" ).val();
        alert(idTrabajo);
        var idEvento = s[s.selectedIndex].value; 
        alert(idEvento);
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/servicio/nuevo/'+ idProyecto + '/' + idTrabajo + '/' + idEvento, 'Nuevo Servicio', '');
    }
    
    </script>
