
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
    <div class="page-header pull-left">
        <div class="page-title">
            <i class="fa fa-briefcase fa-2x" style="font-size: 30px"></i>&nbsp Mis tareas</div>
    </div>
    <ol class="breadcrumb page-breadcrumb pull-right">
        <li><i class="fa fa-home"></i>&nbsp;<a href="sistema">Inicio</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="hidden"><a href="#">Mis tareas</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
        <li class="active">Mis tareas</li>
    </ol>
    <div class="clearfix">
    </div>
</div>

<div class="page-content">
<!--    <div class="tab-content">
        <div class="form-group">
        <div class="row">
            <div class="col-lg-2"  style="text-align: center; margin-top: 5px;">
                <span class="badge badge-red" >URGENTE</span>
                <span class="badge badge-yellow">ALTA</span>
                <span class="badge badge-green">NORMAL</span>
            </div>
            <div class="col-lg-2  col-lg-offset-5">
                <input type="text" class="form-control" placeholder="Nombre del m&oacute;dulo" id="txtModulo">

            </div>
            <div class="col-lg-2">
                <input type="text" class="form-control" placeholder="Nombre de la tarea" id="txtTarea">

            </div>
            <div class="col-lg-1">
                <button class="btn btn-primary"><i class="fa fa-search"></i>&nbsp; Buscar</button>

            </div>
        </div>
        </div>
    </div>-->
    <?php if (@!empty($this->_moduloProyecto)) { ?>
        <?php $cont = 0; ?>
        <div class="row"><?php
            foreach ($this->_moduloProyecto as $modProy) {

                if ($this->_tareas->getTareasUsuario(Session::get('SESS_ID_USER'), $modProy->getIdHito())) {
                    ?>
                    <?php $cont++; ?>
                    <div class="col-lg-3" id="panelModulo">
                        <div class="panel">
                            <div class="panel-heading" id="asd" onclick="mostrarTareas('tarea<?php echo $cont ?>')" style="cursor: pointer">
                                <!--<div class="form-actions text-center">-->
                                <center><?php echo utf8_decode($modProy->getNombre())  ?></center>
                            <!--</div>-->
                            </div>



                            <div class="panel-body pal" id="tarea<?php echo $cont; ?>">
                                <?php
                                if (!empty($this->_tareas)) {
                                    foreach ($this->_tareas->getTareasUsuario(Session::get('SESS_ID_USER'), $modProy->getIdHito()) as $tareaProd) {
                                        ?>  
                                        <div>
                                            <a data-toggle="modal" href="#myModal" onClick="Tarea.prototype.abreModal('<?php echo BASE_URL ?>tarea/abreInfoTicket/<?php echo $tareaProd->getId_evento() ?>', 'Informaci&oacute;n de la Tarea', '<?php echo $tareaProd->getId_evento() ?>')">


                                                <ul class="list-group">
                                                    <?php if ($tareaProd->getId_nivel() == 1) { ?>
                                                        <li class="list-group-item" style="background-color: #dc6767; color: white;"><b><?php echo htmlentities($tareaProd->getNombre(), ENT_QUOTES,'UTF-8') ?></b></li>
                                                    <?php } ?>
                                                    <?php if ($tareaProd->getId_nivel() == 2) { ?>
                                                        <li class="list-group-item" style="background-color: #f0ad4e; color: white;"><b><?php echo htmlentities($tareaProd->getNombre(), ENT_QUOTES,'UTF-8') ?></b></li>

                                                    <?php } ?>
                                                    <?php if ($tareaProd->getId_nivel() == 3) { ?>
                                                        <li class="list-group-item" style="background-color: #5cb85c; color: white;"><b><?php echo htmlentities($tareaProd->getNombre(), ENT_QUOTES,'UTF-8') ?></b></li>

                                                    <?php }
                                                    ?>
                                                    <li class="list-group-item">
                                                        <?php if ($tareaProd->getNombre_evento() == 'Mejora') { ?>
                                                            <i class="fa fa-check"></i>&nbsp <?php echo $tareaProd->getNombre_evento() ?>
                                                        <?php } else if ($tareaProd->getNombre_evento() == 'Incidencia') { ?>
                                                            <i class="fa fa-exclamation-triangle"></i>&nbsp <?php echo $tareaProd->getNombre_evento() ?>
                                                        <?php } else { ?>
                                                            <i class="fa fa-exclamation-circle"></i>&nbsp <?php echo $tareaProd->getNombre_evento() ?>
                                                        <?php }
                                                        ?>

                                                    </li>
<!--                                                    <li class="list-group-item"><i class=""></i><i class="fa fa-clock-o"></i>&nbsp 
                                                        <?php
                                                        if ($tareaProd->getHorasDia() != null && $tareaProd->getHorasDia() > 0) {
                                                            echo $tareaProd->getHorasDia();
                                                        } else {
                                                            echo 'Sin';
                                                        }
                                                        ?> horas dia</li>                              -->
                                                    <li class="list-group-item"><i class="fa fa-calendar"></i>&nbspTerminar antes del 
                                                        <?php
                                                        $date = new DateTime($tareaProd->getFechaTermino());
                                                        echo $date->format('d-m-Y') . ' a las ' . $date->format('H:i') . ' hrs.';
                                                        ?></li>
                                                </ul>
                                            </a>
                                        </div>          
                                    <?php } ?>
                                <?php } ?>

                            </div>
                        </div>

                    </div>

                <?php } ?>        

                <!-- hasta aca itera modulos -->
            <?php } ?>

        <?php } ?>
    </div>

</div>
<script>

    var count = 0;
    var foo = false;
    function mostrarTareas(idx) {

        //var ID = this.id;

        //count++;

        //if (count >= 1) {
        //alert('antes' + count);
        //count -= 3;
        //alert('despues' + count);
        $("#" + idx).fadeIn(1000);
        //foo = true;
        //alert('seleccion true');

//        } else {
//            
//            if (!foo) {
//                ocultarTareas(idx, ID);
//                count += 3;
//                //alert('despues de ocultar sin seleccion antes' + count);
//                foo = false;
//            } else {
//                
//                ocultarTareas(idx, ID);
//                count += 1;
//                //alert('despues de ocultar con seleccion antes' + count);
//                foo = false;
//            }
//        }
        // }
    }
    function ocultarTareas(idx, ID) {
        $("#" + ID).attr("disabled", "disabled");
        $("#" + idx).fadeOut(1000, function () {
            $("#" + ID).removeAttr("disabled");
        });
    }





</script>
<!--<script>
    $("#txtModelo").keyup(function (e) {
        var q = $("#txtModelo").val();
        $.getJSON("http://localhost/GestionTareas/tarea?modelo=",
                {
                    srsearch: q,
                    action: "query",
                    list: "search",
                    format: "json"
                },
                function (data) {
                    $("#panelModulo").empty();
                    $("#panelModulo").append("Results for < b > " + q + " < /b>");
                    $.each(data.query.search, function (i, item) {
                        $("#panelModulo").append("< div > < a href = 'http://localhost/GestionTareas/tarea" + encodeURIComponent(item.title) + "' > " + item.title + " < /a>" + item.snippet + "</div >");
                    });
                });
    });</script>-->
<!--END TITLE & BREADCRUMB PAGE-->
<!--BEGIN CONTENT-->




