<script type="text/javascript" charset="utf-8">
//evento javascript para búsqueda en combo en cascada

//    $("#proyecto").change(function () {
//        $("#proyecto option:selected").each(function () {
//            elegido = $(this).val();
//            $.post('<?php echo BASE_URL ?>/modulo/comboHitos/' + elegido, function (data) {
//                $("#hito").html(data);
//            });
//        });
//    });

</script>

<form class="formSolicitud">
    <div class="row">

        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Proyecto</label>
                <select class="form-control" id="selectProyecto" name="selectProyecto" id="selectProyecto" onchange="cargarTrabajos(this)">
                    <option value="">Seleccione un Proyecto...</option>
                    <?php if ($this->_proyectos) {
                        foreach ($this->_proyectos as $p){ 
                            if($p->getId_producto() == $this->_proyectoSeleccionado){?>
                                 <option selected value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                            <?php }else { ?>
                            <option value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                        <?php }    }              
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Trabajo</label>
                <select class="form-control"  name="selectTrabajo" id="selectTrabajo" onchange="cargarEventos(this)">
                    <option value="">Seleccione un Trabajo...</option>
                    <?php if ($this->_trabajo) {
                        
                        foreach ($this->_trabajo as $t) { 
                            if($t->getIdHito() == $this->_trabajoSeleccionado){ ?>
                                 <option selected value="<?php echo $t->getIdHito() ?>"><?php echo $t->getNombre() ?></option>
                            <?php }else { ?>                                              
                            <option value="<?php echo $t->getIdHito() ?>"><?php echo $t->getNombre() ?></option>                                        
                        <?php  } }
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Evento</label>
                <select class="form-control" name="selectEvento" onchange="cargarAreas(this)">
                    <option value="">Seleccione un Evento...</option>
                    <?php if ($this->_evento) {
                        foreach ($this->_evento as $e) { 
                            if($e->getIdEvento() == $this->_eventoSeleccionado){ ?>
                                 <option selected value="<?php echo $e->getIdEvento() ?>"><?php echo $e->getNombreEvento() ?></option>
                            <?php }else { ?>                                              
                            <option value="<?php echo $e->getIdEvento() ?>"><?php echo $e->getNombreEvento() ?></option>                                        
                    <?php  } 
                        }
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Área</label>
                <select class="form-control" name="selectArea" onchange="cargarServicios(this)">
                    <option value="">Seleccione un Área...</option>
                    <?php if ($this->_areas) {
                        foreach ($this->_areas as $a) {
                            if($a->getIdArea() == $this->_areaSeleccionada){ ?>
                                 <option selected value="<?php echo $a->getIdArea() ?>"><?php echo $a->getNombre() ?></option>
                            <?php }else { ?> 
                            <option value="<?php echo $a->getIdArea() ?>"><?php echo $a->getNombre() ?></option>                                        
                        <?php  } }
                    } ?>
                </select>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Servicio</label>
                <select class="form-control" name="selectServicio" onchange="cargarNiveles(this)">
                    <option value="">Seleccione un Servicio...</option>
                    <?php if ($this->_servicios) {
                        foreach ($this->_servicios as $s) { ?>                                              
                            <option value="<?php echo $s->getIdServicio() ?>"><?php echo $s->getNombreServicio() ?></option>                                        
                    <?php  } 
                    } ?>
                </select>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label>Nivel de Criticidad</label>
                <select class="form-control" name="selectNivel">
                    <option value="">Seleccione un Nivel...</option>
                    <?php if ($this->_niveles) {
                        foreach ($this->_niveles as $n) { ?>                                              
                            <option value="<?php echo $n->getIdNivel() ?>"><?php echo $n->getNombreNivel() ?></option>                                        
                    <?php  } 
                    } ?>
                </select>
            </div>
        </div>

        <div class='col-md-12'>
            <div class="form-group">
                <label>Descripción del Problema</label>
                <!--<input type="text" class="form-control"/>-->
                <textarea cols="10" rows="4" class="form-control" maxlength="200" style="resize: none;" name="txtDescripcion"></textarea>
            </div>
        </div>

        <div class='col-md-12'>
            <div class="form-group">
                <label>Solución Propuesta</label>
<!--                <input type="text" class="form-control"/>-->
                <textarea cols="10" rows="4" class="form-control" maxlength="200" style="resize: none;" name="txtSolucion"></textarea>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label>Adjuntar documento</label>
                <input type="hidden" name="MAX_FILE_SIZE" value="20000">
                <input type="file" name="archivo">
            </div>
        </div>
        <!--            
        
               
        
        
                <div class='col-md-12'>
                    <div class="form-group">
                        <label for ="it_txtaDescripcionProblema">Descripci&oacute;n del problema</label>
                        <textarea style="resize: none;" class="form-control" rows="3" name="it_txtaDescripcionProblema" id="it_txtaDescripcionProblema"></textarea>
                    </div>
        
                </div>
                <div class='col-md-12'>
                    <div class="form-group">
                        <label for ="it_txtaSolucionPropuesta">Soluci&oacute;n Propuesta</label>
                        <textarea style="resize: none;" class="form-control" rows="3" name="it_txtaSolucionPropuesta" id="it_txtaSolucionPropuesta"></textarea>
                    </div>
        
                </div>
        
        
                <div class='col-md-12'>
                    <h5><b>Evento</b></h5>
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-danger">
                                    <input type="radio" name="rdbtnTipoologia" id="rdbtnTipoologia" value="1">
                                    Falla &nbsp;  &nbsp;  &nbsp;  &nbsp; &nbsp; 
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-warning">
                                    <input type="radio" name="rdbtnTipoologia" id="rdbtnTipoologia2" value="2">
                                    Incidencia
                                </label>
                            </div>
                        </div>
                    </div>
        
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-success">
                                    <input type="radio" name="rdbtnTipoologia" id="rdbtnTipoologia3" value="3" checked>
                                    Mejora &nbsp;  &nbsp; &nbsp;
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
        
                <div class='col-md-12'>
                    <h5><b>Nivel</b></h5>
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-danger">
                                    <input type="radio" name="rdbtnPrioridad" id="rdbtnPrioridad1" value="1">
                                    Urgente&nbsp; &nbsp;
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-warning">
                                    <input type="radio" name="rdbtnPrioridad" id="rdbtnPrioridad2" value="2">
                                    Alta&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                                </label>
                            </div>
                        </div>
                    </div>
        
                    <div class='col-md-2'>
                        <div class="form-group">
                            <div class="radio">
                                <label class="label label-success">
                                    <input type="radio" name="rdbtnPrioridad" id="rdbtnPrioridad3" value="3" checked>
                                    Normal&nbsp; &nbsp; &nbsp;
                                </label>
                            </div>
                        </div>
                    </div>
                </div>-->

        <div class="col-md-12">
            <div class="form-group text-right">
                <!--<button type="button" class="btn btn-yellow">Guardar e Imprimir</button>-->
                <button type="button" id="btnGuardarTarea" class="btn btn-yellow" data-toggle="modal" href="#myModal" 
                        onClick="Modulo.prototype.procesoEnviaForm('formSolicitud',
                                        '<?php echo BASE_URL ?>modulo/insertSolicitud',
                                        'btnGuardarTarea',
                                        '<?php
                        if (Session::get('SESS_ID_TIPO_USER') == 2) {
                            echo BASE_URL . 'tarea';
                        } else if (Session::get('SESS_ID_TIPO_USER') == 3) {
                            echo BASE_URL . 'avance';
                        } else if (Session::get('SESS_ID_TIPO_USER') == 1 || Session::get('SESS_ID_TIPO_USER') == 0) {
                            echo BASE_URL . 'modulo';
                        }
                        ?>')" 
                        id="btnGuardarTarea"  name="btnGuardarTarea" aria-haspopup="true" aria-expanded="false">
                    Guardar
                </button>
               
            </div>
        </div>




    </div>
</form>

<script>
    
    function cargarTrabajos(s){
      
        var idProyecto = s[s.selectedIndex].value; 
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/modulo/abreSolicitudTareas/'+idProyecto, 'Crear nueva solicitud de tarea', '');
    }
    
    function cargarEventos(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        var idTrabajo = s[s.selectedIndex].value; 
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/modulo/abreSolicitudTareas/'+ idProyecto + '/' + idTrabajo, 'Crear nueva solicitud de tarea', '');
    }
    
    function cargarAreas(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        var idTrabajo = $( "#selectTrabajo" ).val();
        var idEvento = s[s.selectedIndex].value; 
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/modulo/abreSolicitudTareas/'+ idProyecto + '/' + idTrabajo + '/' + idEvento, 'Crear nueva solicitud de tarea', '');
    }
    
    function cargarServicios(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        var idTrabajo = $( "#selectTrabajo" ).val();
        var idEvento = $( "#selectEvento" ).val();
        var idArea = s[s.selectedIndex].value;
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/modulo/abreSolicitudTareas/'+ idProyecto + '/' + idTrabajo + '/' + idEvento + '/' + idArea, 'Crear nueva solicitud de tarea', '');
    }
    
    function cargarNiveles(s){
        
        var idProyecto = $( "#selectProyecto" ).val();
        var idTrabajo = $( "#selectTrabajo" ).val();
        var idEvento = $( "#selectEvento" ).val();
        var idArea = $( "#selectArea" ).val();
        var idServicio = s[s.selectedIndex].value;
        
        Servicio.prototype.abreModal('<?php echo BASE_URL ?>/modulo/abreSolicitudTareas/'+ idProyecto + '/' + idTrabajo + '/' + idEvento + '/' + idArea + '/' + idServicio, 'Crear nueva solicitud de tarea', '');
    }
    
</script>