<div class="row">
    <form class="form" method="post">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Proyecto</label>
                <select class="form-control" name="selectProyecto" id="selectProyecto" onchange="cargarTrabajos(this)">
                    <option value="0">Seleccione un Proyecto...</option>
                    <?php if ($this->_proyectos) {
                        foreach ($this->_proyectos as $p){ 
                            if($p->getId_producto() == $this->_seleccionado){?>
                                 <option selected value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                            <?php }else { ?>
                            <option value="<?php echo $p->getId_producto() ?>"><?php echo $p->getNombre() ?></option>
                        <?php }    }              
                    } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Trabajo</label>
                <select class="form-control" name="selectTrabajo">
                    <option value="0">Seleccione un Trabajo...</option>
                    <?php if ($this->_trabajo) { ?>                                              
                            <option><?php echo $this->_trabajo->getNombre() ?></option>                                        
                    <?php  } ?>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Tipificación de Evento</label>
                <input type="text" name="txtNemo" class="form-control">
            </div>
        </div>
<!--        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label">Cliente</label>
                <select class="form-control" name="selectClientes">
                    <?php
                    if ($this->_clientes) {
                        foreach ($this->_clientes as $c) {
                            ?>
                            <option value="<?php echo $c->getId() ?>"><?php echo $c->getNombre() ?></option>
                            <?php
                        }
                    }
                    ?>
                </select>
            </div>
        </div>-->
        <div class="col-md-12">
            <div class="form-group text-right">
                    <button type="submit" id="btn" class="btn btn-yellow" onclick="Evento.prototype.procesoEnviaForm('form', '<?php echo BASE_URL ?>evento/ingresar', 'btn', '<?php echo BASE_URL ?>evento')">Guardar</button>
            </div>
        </div>
    </form>
</div>

<script>
    
    function cargarTrabajos(s){
      
        var id = s[s.selectedIndex].value; 
        
        Evento.prototype.abreModal('<?php echo BASE_URL ?>/evento/nuevo/'+id, 'Nuevo Evento', '');
    }
    
    </script>